#!/usr/bin/env python3
"""Deterministic Skill Builder V1.

This is a compiler-like offline baseline. It does not call an LLM and never
claims semantic validation or external execution.
"""
from __future__ import annotations
import json, sys
from pathlib import Path

REQUIRED = ["task_id", "task", "inputs", "outcome", "quality", "failure"]
OPTIONAL = ["dependencies", "evidence", "constraints"]


def as_list(value, field):
    if isinstance(value, list):
        if not value:
            raise ValueError(f"{field} must not be empty")
        return [str(x).strip() for x in value if str(x).strip()]
    if isinstance(value, str) and value.strip():
        return [value.strip()]
    raise ValueError(f"{field} must be a non-empty string or list")


def bullets(items):
    return "\n".join(f"- {x}" for x in items)


def build(spec):
    missing = [k for k in REQUIRED if k not in spec]
    if missing:
        raise ValueError(f"missing required fields: {', '.join(missing)}")
    if not isinstance(spec["task_id"], str) or not spec["task_id"].strip():
        raise ValueError("task_id must be a non-empty string")
    if not isinstance(spec["task"], str) or not spec["task"].strip():
        raise ValueError("task must be a non-empty string")

    inputs = as_list(spec["inputs"], "inputs")
    quality = as_list(spec["quality"], "quality")
    failure = as_list(spec["failure"], "failure")

    lines = [
        f"# Skill Candidate — {spec['task_id']}",
        "",
        "> Generated by Skill Builder V1 deterministic offline baseline.",
        "> Evidence state: OFFLINE-MOCK. This candidate has not been externally executed.",
        "",
        "## Purpose / Boundary",
        spec["task"].strip(),
        "",
        "## Inputs",
        bullets(inputs),
        "",
        "## Procedure",
        "1. Accept and interpret only the supplied inputs relevant to the task.",
        "2. Perform the task described by the Purpose / Boundary.",
        "3. Return the defined Outcome while preserving the listed Quality Conditions.",
        "4. If required information or capability is missing, follow Failure / Uncertainty instead of inventing it.",
        "",
        "## Outcome",
        spec["outcome"].strip(),
        "",
        "## Quality Conditions",
        bullets(quality),
        "",
        "## Failure / Uncertainty",
        bullets(failure),
    ]

    for field, title in (("dependencies", "Dependencies"), ("evidence", "Evidence Rules"), ("constraints", "Constraints")):
        if field in spec:
            values = as_list(spec[field], field)
            lines += ["", f"## {title}", bullets(values)]

    return "\n".join(lines).rstrip() + "\n"


def main():
    if len(sys.argv) not in (2, 3):
        print("usage: build_skill_v1.py <input.json> [output.md]", file=sys.stderr)
        return 2
    source = Path(sys.argv[1])
    try:
        spec = json.loads(source.read_text(encoding="utf-8"))
        candidate = build(spec)
    except (OSError, json.JSONDecodeError, ValueError) as exc:
        print(json.dumps({"status":"REJECTED","reason":str(exc)}, ensure_ascii=False))
        return 1
    if len(sys.argv) == 3:
        Path(sys.argv[2]).write_text(candidate, encoding="utf-8")
    print(candidate, end="")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
